export const JWT_PASSWORD = process.env.JWT_PASSWORD || "AREYOUSERIOUSABOUTYOURSTUDIES"
export const ADMIN_JWT_PASSWORD = process.env.JWT_PASSWORD || "AREYOUFUCKINGSERIOUSABOUTYOURSTUDIES"
export const TOPT_SECRET = process.env.TOPT_SECRET || "AREYOUSERIOUSABOUTYOURSTUDIES";
export const TWILIO_ACCOUNT_SID = process.env.TWILIO_SID
export const TWILIO_AUTH_TOKEN = process.env.TWILIO_TOKEN